version: '2.4'

services:
  octoprint:
    container_name: octoprint
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 80:4000
    devices:
    # use `python -m serial.tools.miniterm` to see what the name is of the printer
     - /dev/ttyUSB0:/dev/ttyACM0
     - /dev/video0:/dev/video0
    volumes:
     - octoprint:/octoprint
    # uncomment the lines below to ensure camera streaming is enabled when
    # you add a video device
    environment:
     - ENABLE_MJPG_STREAMER=true
  
  #config-editor:
  #  image: linuxserver/code-server
  #  ports:
  #    - 8443:8443
  #  depends_on:
  #    - octoprint
  #  restart: unless-stopped
  #  environment:
  #    - PUID=0
  #    - GUID=0
  #    - TZ=America/Chicago
  #  volumes:
  #    - octoprint:/octoprint

volumes:
  octoprint: